### ISSUE TITLE
Request to remove personal information

### ISSUE THREAD

**Issue by somin5573** [pypi-data/pypi-json-data#10]
Hi, Could you remove this repogitory?
url: https://github.com/pypi-data/pypi-json-data/blob/4b9a3600d42258708f7453349f9d24b8867e077c/release_data/s/k/skkwiaaisi.json
It's against my company's policy to release them.
Personal information (email) of our company's employees, DB access information is included. 
Please remove it..!

**Comment by orf** [comment]
Please reach out to PyPi
